spring.datasource.url=jdbc:postgresql://db:5432/avanza
spring.datasource.username=avanza
spring.datasource.password=avanza123
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8082
spring.thymeleaf.cache=false
